### ISSUE TITLE
Adjust collision meshes

### ISSUE THREAD

**Issue by codekansas** [kscalelabs/onshape#22]
Right now, collision meshes cause some issues. There are a couple of possible features to add here:

1. Combine meshes which use a fixed joint into a single mesh, sharing inertias
2. Make collision meshes slightly smaller than the original mesh
3. Selectively remove or simplify some meshes

**Comment by kiluazen** [comment]
Hey @codekansas , are kscalelabs repositories open for contributions. I am interested in RL, robotics. Thought contributing to your work will be a good learning opportunity.

**Comment by codekansas** [comment]
@kiluazen absolutely open for contributions! feel free to submit a pr :)

**Comment by codekansas** [comment]
Partially addressed by #20
