### ISSUE TITLE
Question about mass properties

### ISSUE THREAD

**Issue by emrecemal** [kscalelabs/onshape#41]
Hello,

Thank you for the nice repository! I have a question about the generated MJCF file. When I check the generated file, I don't see any definition related to mass properties like inertia. Do I need to add them separately?

**Comment by budzianowski** [comment]
Hi @emrecemal  - thanks for raising this! I have created explicit flag for urdf and mjcf creation: https://github.com/kscalelabs/onshape/pull/42

**Comment by emrecemal** [comment]
Thank you for the improvement. However, I couldn't get the update on my local even if I tried to reinstall directly from Github using this code:
`pip install 'kscale-onshape-library @ git+https://github.com/kscalelabs/onshape.git@master'`

**Comment by budzianowski** [comment]
What do you mean by 'get the update'?

**Comment by emrecemal** [comment]
I get this error:

```
usage: kol [-h] [-o OUTPUT_DIR] [--debug] document_url
kol: error: unrecognized arguments: --remove_inertia
```

**Comment by emrecemal** [comment]
I think the problem was related to the Python version. I was using Python 3.12 while it should have been Python 3.11. Downgrading the version fixed the problem!
